spring:
  application:
    name: tandem-api
  profiles:
     active: dev
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    open-in-view: false
  flyway:
    enabled: true
    locations: classpath:db/migration

server:
  port: 8080
  servlet:
    context-path: /api/v1



springdoc:
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
  api-docs:
    enabled: true


jwt:
  secret: ${JWT_SECRET}
  access-expiry: ${ACCESS_EXPIRY}
  refresh-expiry: ${REFRESH_EXPIRY}